language: node_js
node_js: node
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "firefox-bin -v"
  - "DEBUG=launchpad:* node node_modules/testee/bin/testee test/test.html --browsers firefox"
addons:
  firefox: latest
